// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igcuxpbeumvpwaaefomw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlnY3V4cGJldW12cHdhYWVmb213Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MTY1NjQsImV4cCI6MjA2MDI5MjU2NH0.9mi1iSRtZTNeDF48vsC2nMObxBYzvQahpYl9Dov8TVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);